---
- name: Stop and Remove Previous Database Container
  docker_container:
    name: database
    state: absent

- name: Remove Old Database Image
  docker_image:
    name: skyward67/devopsdatabase:latest
    state: absent

- name: Launch Database container
  docker_container:
    name: database
    image: skyward67/devopsdatabase:latest
    state: started
    networks:
      - name: app-network
    env:
      POSTGRES_USER: "{{ lookup('env', 'DATABASE_USER') }}"
      POSTGRES_PASSWORD: "{{ lookup('env', 'DATABASE_PASS') }}"
      POSTGRES_DB: "{{ lookup('env', 'DATABASE_NAME') }}"