---
- name: Stop and Remove Previous Database Container
  docker_container:
    name: database
    state: absent

- name: Remove Old Database Image
  docker_image:
    name: skyward67/devopsdatabase:latest
    state: absent

- name: Launch Database container
  docker_container:
    name: database
    image: skyward67/devopsdatabase:latest
    state: started
    networks:
      - name: app-network
    env:
      POSTGRES_USER: "{{ database_user }}"
      POSTGRES_PASSWORD: "{{ database_pass }}"
      POSTGRES_DB: "{{ database_name }}"