---
- name: Stop and Remove Previous Database Container
  docker_container:
    name: database
    state: absent
  vars:
    DATABASE_USER: "{{ lookup('env', 'DATABASE_USER') }}"
    DATABASE_PASS: "{{ lookup('env', 'DATABASE_PASS') }}"
    DATABASE_NAME: "{{ lookup('env', 'DATABASE_NAME') }}"

- name: Remove Old Database Image
  docker_image:
    name: skyward67/devopsdatabase:latest
    state: absent

- name: Launch Database container
  docker_container:
    name: database
    image: skyward67/devopsdatabase:latest
    state: started
    networks:
      - name: app-network
    env:
      POSTGRES_USER: "{{ DATABASE_USER }}"
      POSTGRES_PASSWORD: "{{ DATABASE_PASS }}"
      POSTGRES_DB: "{{ DATABASE_NAME }}"