---
- name: Stop and Remove Previous Backend Container
  docker_container:
    name: api
    state: absent

- name: Remove Old Backend Image
  docker_image:
    name: skyward67/devopsbackend:latest
    state: absent


- name: Deploy Backend User Service
  docker_swarm_service:
    name: "{{ backend_service_name }}"
    state: present
    image: "{{ backend_image }}"
    replicas: "{{ backend_replicas }}"
    networks:
      - "{{ backend_network }}"
    endpoint_mode: vip
    ports:
      - "{{ backend_port }}:{{ backend_port }}"