---
- name: Stop and Remove Previous Backend Container
  docker_container:
    name: api
    state: absent

- name: Remove Old Backend Image
  docker_image:
    name: skyward67/devopsbackend:latest
    state: absent


- name: Run Backend User Container
  docker_container:
    name: backend_user
    image: "{{ backend_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ backend_port }}:{{ backend_port }}"