---
- name: Stop and Remove Previous Backend Container
  docker_container:
    name: api
    state: absent

- name: Remove Old Backend Image
  docker_image:
    name: skyward67/devopsbackend:latest
    state: absent

- name: Launch Backend API
  docker_container:
    name: api
    image: skyward67/devopsbackend:latest
    state: started
    networks:
      - name: app-network
    env:
      POSTGRES_USER: "{{ lookup('env', 'DATABASE_USER') }}"
      POSTGRES_PASSWORD: "{{ lookup('env', 'DATABASE_PASS') }}"
      POSTGRES_DB: "{{ lookup('env', 'DATABASE_NAME') }}"