---
- name: Stop and Remove Previous Proxy Container
  docker_container:
    name: web
    state: absent

- name: Remove Old Proxy Image
  docker_image:
    name: "{{ proxy_image }}"
    state: absent
  
- name: Pull Proxy Image
  docker_image:
    name: "{{ proxy_image }}"
    source: pull


- name: Configure Apache Virtual Hosts
  template:
    src: /TP01/Web/apache-reverse-proxy.conf
    dest: /etc/apache2/sites-available/proxy.conf

- name: Enable Apache Virtual Host
  apache2_module:
    state: present
    name: proxy

- name: Enable Apache Proxy Module
  apache2_module:
    state: present
    name: proxy_http

- name: Enable Apache Balancer Module
  apache2_module:
    state: present
    name: proxy_balancer

- name: Enable Load Balancing Method Module
  apache2_module:
    state: present
    name: lbmethod_byrequests

- name: Enable Apache Virtual Host Configuration
  apache2_vhost:
    state: present
    force: true
    filename: proxy.conf

- name: Restart Apache Service
  service:
    name: apache2
    state: restarted