---
- name: Stop and Remove Previous Proxy Container
  docker_container:
    name: web
    state: absent

- name: Remove Old Proxy Image
  docker_image:
    name: skyward67/devopsweb:latest
    state: absent

- name: Launch Proxy
  docker_container:
    name: web
    image: skyward67/devopsweb:latest
    state: started
    networks:
      - name: app-network
    ports:
      - "81:80"