name: Deploy with Ansible

on:
  workflow_run:
    workflows: ["CD devops 2023"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Action to checkout the repository code
      
      - name: Install Python and Ansible
        uses: actions/setup-python@v2
        with:
          python-version: '3'  # Choose Python version
      - name: Install dependencies
        run: pip install ansible
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_ANSIBLE }}
      
      - name: Run Ansible playbook
        run: ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml  # Replace with the name of your Ansible playbook file
        env:
          ANSIBLE_HOST_KEY_CHECKING: false # Disable host key checking
      
      # Add additional steps as needed for testing, deployment, etc.
