name: Deploy with Ansible

on:
  workflow_run:
    workflows: ["CD devops 2023"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Action to checkout the repository code
      
      - name: Install Python and Ansible
        uses: actions/setup-python@v2
        with:
          python-version: '3'  # Choose Python version
      - name: Install dependencies
        run: pip install ansible
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_ANSIBLE }}
      
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
            # Required, playbook filepath, relative to the repository root
            playbook: ansible/playbook.yml
            # Optional, SSH private key to connect to the target host
            key: ${{secrets.SSH_ANSIBLE}}
            # Optional, literal inventory file contents, in our case, we only got one server so we put it's address in the inventory
            inventory: |
                ansible/inventories/setup.yml
            # Optional, encrypted vault password, so we access the vault environment variables without any risque
            vault_password: ${{secrets.VAULT}}
            # Optional, extra arguments to pass to the ansible-playbook command, we use `-u` to specify the user to connect to the server, else we can't connect
            options: |
                --verbose
