name: Deploy with Ansible

on:
  workflow_run:
    workflows: ["CD devops 2023"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Action to checkout the repository code
      
      - name: Install Python and Ansible
        uses: actions/setup-python@v2
        with:
          python-version: '3'  # Choose Python version
      - name: Install dependencies
        run: pip install ansible
      
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: TP03/ansible/playbook.yml
          key: ${{ secrets.SSH_ANSIBLE }}
          inventory: |
            [all]
            dorian.gorse.takima.cloud
