name: Build and Push Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "This is a dummy step"

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./TP01/API
          tags: ${{secrets.DOCKERHUB_USERNAME}}/devopsbackend:latest
          push: true

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./TP01/database
          tags: ${{secrets.DOCKERHUB_USERNAME}}/devopsdatabase:latest
          push: true

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./TP01/Web
          tags: ${{secrets.DOCKERHUB_USERNAME}}/devopsweb:latest
          push: true
