name: CI devops 2023

on:
  push:
    branches: 
      - main

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Change directory to TP01/API
        run: cd TP01/API

      - name: Build and test with Maven
        run: mvn -f TP01/API/pom.xml test

  # define job to build and publish docker image
  build-and-push-docker-image:
  needs: test-backend
  # run only when code is compiling and tests are passing
  runs-on: ubuntu-22.04

  # steps to perform in job
  steps:
    - name: Checkout code
      uses: actions/checkout@v2.5.0

    - name: Build image and push backend
      uses: docker/build-push-action@v3
      with:
        # relative path to the place where source code with Dockerfile is located
        context: ./TP01/API
        # Note: tags has to be all lower-case
        tags:  skyward67/devopsbackend:latest

    - name: Build image and push database
        # relative path to the place where source code with Dockerfile is located
        context: ./TP01/database
        # Note: tags has to be all lower-case
        tags:  skyward67/devopsdatabase:latest

    - name: Build image and push httpd
        # relative path to the place where source code with Dockerfile is located
        context: ./TP01/Web
        # Note: tags has to be all lower-case
        tags:  skyward67/devopsweb:latest
